version: '3.4'

services:
    go:
        image: golang:latest
        container_name: go
        working_dir: /go/src/app
        volumes:
        - "./..:/go/src/app"
        command: go run main.go
        depends_on:
        - redis
    redis:
        restart: always
        image: redis:alpine
        container_name: redis_db
        ports:
          - "6379:6379"
    redis-commander:
        image: rediscommander/redis-commander:latest
        environment:
          - REDIS_HOSTS=local:redis_db:6379
        ports:
          - 8081:8081
        depends_on:
          - redis